checks if the sqlite and sqlite3 binaries exists. Fixes bgo #467010. Thx
2007-09-23  Stephane Delcroix  <stephane@delcroix.org>

	* tools/f-spot-sqlite-upgrade: checks if the sqlite and sqlite3
	binaries exists. Fixes bgo #467010. Thx goes to Giacomo Rizzo.

svn path=/trunk/; revision=3396

diff --git a/tools/f-spot-sqlite-upgrade b/tools/f-spot-sqlite-upgrade
--- a/tools/f-spot-sqlite-upgrade
+++ b/tools/f-spot-sqlite-upgrade
@@ -4,6 +4,14 @@
 DB_LOCATION=~/.gnome2/f-spot/photos.db
 BACKUP_LOCATION=$DB_LOCATION.backup
 
+if ! which sqlite >& /dev/null ; then
+	echo "Could not find sqlite binary. Update aborted."
+	exit 1
+elif ! which sqlite3 >& /dev/null ; then
+	echo "Could not find sqlite3 binary. Update aborted."
+	exit 1
+fi
+
 if grep "^...This file contains an SQLite 2.1 database" $DB_LOCATION &> /dev/null; then
 	echo "Upgrading from SQLite 2.1 to SQLite3"
 	mv $DB_LOCATION $BACKUP_LOCATION
